/**
 * CIReportGenerator
 * PHASE 1.3 — Architectural CI
 *
 * Transforms raw pipeline results into formatted reports for CI/CD integration.
 * Generates JSON (structured), Markdown (human-readable), and JUnit XML (tool-compatible).
 * Pure transformer with no external dependencies beyond fs and path.
 *
 * Responsibilities:
 * - Generate JSON reports with canonical structure
 * - Generate Markdown reports with readable formatting and status badges
 * - Generate JUnit XML reports compatible with GitHub Actions, GitLab CI, Jenkins
 * - Save reports to disk with automatic directory creation
 * - Provide report generation metrics and history
 */

const fs = require('fs');
const path = require('path');

class CIReportGenerator {
  constructor(options = {}) {
    if (!options) throw new Error('options required');

    this.config = {
      outputDir: options.outputDir || path.join(process.cwd(), 'ci-reports'),
      includeTimestamp: options.includeTimestamp !== false,
      junitTestSuiteName: options.junitTestSuiteName || 'CitoyenAvise Constitutional CI'
    };

    this.generatedReports = [];
    this.metrics = {
      reportsGenerated: 0,
      jsonReports: 0,
      markdownReports: 0,
      junitReports: 0,
      totalSizeBytes: 0
    };
  }

  /**
   * Generate JSON report from pipeline result
   * Structure: { meta, timestamp, summary, stages, violations, verdict }
   */
  generateJSONReport(pipelineResult) {
    if (!pipelineResult) throw new Error('pipelineResult required');

    const report = {
      meta: {
        format: 'json',
        phase: '1.3-ci',
        generator: 'CIReportGenerator',
        timestamp: new Date().toISOString()
      },
      summary: {
        success: pipelineResult.success,
        exitCode: pipelineResult.success ? 0 : 1,
        duration_ms: pipelineResult.duration_ms || 0,
        stagesCount: pipelineResult.stages ? pipelineResult.stages.length : 0,
        violationsCount: this._countViolations(pipelineResult)
      },
      stages: pipelineResult.stages || [],
      violations: this._extractViolations(pipelineResult),
      verdict: pipelineResult.success ? 'PASS' : 'FAIL'
    };

    const content = JSON.stringify(report, null, 2);
    this.metrics.jsonReports += 1;
    this.metrics.totalSizeBytes += content.length;

    return {
      format: 'json',
      content,
      report
    };
  }

  /**
   * Generate Markdown report for human readability
   */
  generateMarkdownReport(pipelineResult) {
    if (!pipelineResult) throw new Error('pipelineResult required');

    const timestamp = new Date().toISOString();
    const badge = pipelineResult.success ? '✅ PASS' : '❌ FAIL';
    const exitCode = pipelineResult.success ? 0 : 1;
    const violations = this._extractViolations(pipelineResult);

    let markdown = `# Constitutional CI Report\n\n`;
    markdown += `**${badge}** | Exit Code: ${exitCode}\n\n`;
    markdown += `Generated: ${timestamp}\n\n`;
    markdown += `---\n\n`;

    markdown += `## Summary\n\n`;
    markdown += `| Metric | Value |\n`;
    markdown += `|--------|-------|\n`;
    markdown += `| Status | ${pipelineResult.success ? 'PASS' : 'FAIL'} |\n`;
    markdown += `| Duration | ${pipelineResult.duration_ms || 0}ms |\n`;
    markdown += `| Stages Run | ${pipelineResult.stages ? pipelineResult.stages.length : 0} |\n`;
    markdown += `| Violations Found | ${violations.length} |\n\n`;

    markdown += `## Stages\n\n`;
    if (pipelineResult.stages && pipelineResult.stages.length > 0) {
      for (const stage of pipelineResult.stages) {
        const stageStatus = stage.success ? '✅' : '❌';
        markdown += `- ${stageStatus} **${stage.stage}**\n`;
      }
      markdown += '\n';
    }

    if (violations.length > 0) {
      markdown += `## Violations (${violations.length})\n\n`;
      markdown += `| Type | Severity | Message |\n`;
      markdown += `|------|----------|----------|\n`;
      for (const v of violations) {
        markdown += `| ${v.type || 'UNKNOWN'} | ${v.severity || 'UNKNOWN'} | ${v.message || 'N/A'} |\n`;
      }
      markdown += '\n';
    }

    markdown += `---\n\nGenerated by CitoyenAvise Constitutional CI (Phase 1.3)`;

    const content = markdown;
    this.metrics.markdownReports += 1;
    this.metrics.totalSizeBytes += content.length;

    return {
      format: 'markdown',
      content
    };
  }

  /**
   * Generate JUnit XML report for CI tools
   */
  generateJUnitReport(pipelineResult) {
    if (!pipelineResult) throw new Error('pipelineResult required');

    const violations = this._extractViolations(pipelineResult);
    const failureCount = violations.length;
    const testCount = (pipelineResult.stages ? pipelineResult.stages.length : 0) + (failureCount > 0 ? 1 : 0);

    let xml = '<?xml version="1.0" encoding="UTF-8"?>\n';
    xml += `<testsuite name="${this._escapeXml(this.config.junitTestSuiteName)}" `;
    xml += `tests="${testCount}" failures="${failureCount}" timestamp="${new Date().toISOString()}">\n`;

    // Each stage as a testcase
    if (pipelineResult.stages && pipelineResult.stages.length > 0) {
      for (const stage of pipelineResult.stages) {
        xml += `  <testcase name="${this._escapeXml(stage.stage)}" classname="Phase1.3.CI" time="0">\n`;
        if (!stage.success) {
          xml += `    <failure message="Stage failed">${this._escapeXml(stage.details || 'No details')}</failure>\n`;
        }
        xml += `  </testcase>\n`;
      }
    }

    // Violations as separate testcase
    if (violations.length > 0) {
      xml += `  <testcase name="Violations" classname="Phase1.3.CI" time="0">\n`;
      const violationDetails = violations
        .map((v) => `${v.severity || 'UNKNOWN'}: ${v.message || 'N/A'}`)
        .join('\n');
      xml += `    <failure message="${violations.length} violations found">${this._escapeXml(violationDetails)}</failure>\n`;
      xml += `  </testcase>\n`;
    }

    xml += `</testsuite>\n`;

    this.metrics.junitReports += 1;
    this.metrics.totalSizeBytes += xml.length;

    return {
      format: 'junit',
      content: xml
    };
  }

  /**
   * Save a report to disk
   */
  saveReport(report, filename) {
    if (!report || !filename) throw new Error('report and filename required');

    try {
      // Create output directory if it doesn't exist
      if (!fs.existsSync(this.config.outputDir)) {
        fs.mkdirSync(this.config.outputDir, { recursive: true });
      }

      const filepath = path.join(this.config.outputDir, filename);
      fs.writeFileSync(filepath, report.content, 'utf8');

      this.generatedReports.push({
        format: report.format,
        filename,
        filepath,
        savedAt: new Date().toISOString(),
        sizeBytes: report.content.length
      });

      return {
        saved: true,
        path: filepath,
        sizeBytes: report.content.length
      };
    } catch (error) {
      return {
        saved: false,
        error: error.message
      };
    }
  }

  /**
   * Generate all 3 formats at once
   */
  generateAllFormats(pipelineResult) {
    if (!pipelineResult) throw new Error('pipelineResult required');

    const json = this.generateJSONReport(pipelineResult);
    const markdown = this.generateMarkdownReport(pipelineResult);
    const junit = this.generateJUnitReport(pipelineResult);

    this.metrics.reportsGenerated += 3;

    return [json, markdown, junit];
  }

  /**
   * Get all generated reports
   */
  getGeneratedReports() {
    return [...this.generatedReports];
  }

  /**
   * Get current status
   */
  getStatus() {
    return {
      timestamp: new Date().toISOString(),
      metrics: { ...this.metrics },
      outputDir: this.config.outputDir,
      reportsGenerated: this.generatedReports.length
    };
  }

  /**
   * Reset state (for testing)
   */
  reset() {
    this.generatedReports = [];
    this.metrics = {
      reportsGenerated: 0,
      jsonReports: 0,
      markdownReports: 0,
      junitReports: 0,
      totalSizeBytes: 0
    };
    return { reset: true };
  }

  /**
   * Private: Count total violations in pipeline result
   */
  _countViolations(pipelineResult) {
    let count = 0;
    if (pipelineResult.stages) {
      for (const stage of pipelineResult.stages) {
        if (stage.violations && Array.isArray(stage.violations)) {
          count += stage.violations.length;
        }
      }
    }
    return count;
  }

  /**
   * Private: Extract flat list of violations
   */
  _extractViolations(pipelineResult) {
    const violations = [];
    if (pipelineResult.stages) {
      for (const stage of pipelineResult.stages) {
        if (stage.violations && Array.isArray(stage.violations)) {
          violations.push(...stage.violations);
        }
      }
    }
    return violations;
  }

  /**
   * Private: Escape XML special characters
   */
  _escapeXml(str) {
    if (typeof str !== 'string') return String(str);
    return str
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&apos;');
  }
}

module.exports = CIReportGenerator;
